// <auto-generated />
namespace BuyArt.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrationOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202009281434189_migrationOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
